name: Lint & Test

on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]

env:
  CI: true
  DEBIAN: noninteractive

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: leafo/gh-actions-lua@v8.0.0
      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install LuaCheck
        run: luarocks install luacheck

      - name: Install task runner
        run: |
          mkdir ~/just && cd ~/just
          wget https://github.com/casey/just/releases/download/1.0.1/just-1.0.1-x86_64-unknown-linux-musl.tar.gz
          tar -xvf just-1.0.1-x86_64-unknown-linux-musl.tar.gz
          sudo install ./just /usr/local/bin/just

      - name: Run checks
        run: just check --formatter TAP

  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ['5.1', '5.2', '5.3', '5.4', 'luajit']
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install Busted
        run: luarocks install busted

      - name: Install task runner
        run: |
          mkdir ~/just && cd ~/just
          wget https://github.com/casey/just/releases/download/1.0.1/just-1.0.1-x86_64-unknown-linux-musl.tar.gz
          tar -xvf just-1.0.1-x86_64-unknown-linux-musl.tar.gz
          sudo install ./just /usr/local/bin/just

      - name: Run tests
        run: just test --output=TAP
